"""Offline synthetic preflight CLI and reproducible static-demo data generator."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shipping.preflight import browser_demo, build_preflight, checklist, demo_packet


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="demo-output/preflight")
    parser.add_argument("--input", type=Path, help="Check a packet JSON containing shipment, scope, documents and observations")
    parser.add_argument("--write-browser-data", action="store_true", help="Regenerate docs/demo/data.js from Python rules")
    args = parser.parse_args()
    if args.input and args.write_browser_data:
        parser.error("--input cannot be combined with --write-browser-data")
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    if args.input:
        try:
            packet = json.loads(args.input.read_text(encoding="utf-8"))
            report = build_preflight(**packet)
        except ArithmeticError:
            print("预检输入无效：数值计算超出支持的精度，请检查金额与计价换算。", file=sys.stderr)
            return 1
        except (OSError, ValueError, TypeError, KeyError) as error:
            print(f"预检输入无效：{error}", file=sys.stderr)
            return 1
        (out / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{report['status']}: {report['summary']['passed']}/{report['summary']['required']} matched; report: {out / 'report.json'}")
        return 0 if report["status"] == "READY_FOR_HUMAN_REVIEW" else 2
    for name, corrected in [("before", False), ("after", True)]:
        packet = demo_packet(corrected=corrected)
        report = build_preflight(**packet)
        for suffix, data in [("input", packet), ("report", report)]:
            (out / f"{name}-{suffix}.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{name}: {report['summary']['passed']}/{report['summary']['required']} matched; {report['status']}")
    if args.write_browser_data:
        target = Path(__file__).resolve().parents[1] / "docs/demo/data.js"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("// Generated by scripts/preflight_demo.py; SYNTHETIC ONLY.\nwindow.PREFLIGHT_DEMO = "
                          + json.dumps(browser_demo(), ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
        for scenario, corrected in [("problem", False), ("corrected", True)]:
            packet = demo_packet(corrected)
            labels = {c["id"]: c["field_label"] for c in checklist(packet["shipment"], packet["scope"])}
            folder = target.parent / "sources" / scenario
            folder.mkdir(parents=True, exist_ok=True)
            for document in packet["documents"]:
                lines = ["SYNTHETIC TEST DOCUMENT — 全部为合成演示内容，不可用于出运。", ""]
                for observation in packet["observations"]:
                    if observation["document_id"] == document["id"]:
                        unit = observation.get("unit")
                        suffix = " " + unit if unit and unit != "amount" else ""
                        lines.append(f"{labels[observation['check_id']]}: {observation['value'] or '[未提供]'}{suffix}")
                (folder / document["file_name"]).write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
